CFLAGS = -std=c++11
CC = g++

target:main

main: main.cpp Robot.cpp Robot.h Bulldozer.cpp Bulldozer.h Humanic.cpp Humanic.h Optimusprime.h Optimusprime.cpp Robocop.cpp Robocop.h Roomba.cpp Roomba.h
	$(CC) $(CFLAGS)  main.cpp Robot.cpp  Bulldozer.cpp Humanic.cpp Optimusprime.cpp Robocop.cpp Roomba.cpp -o main 
clean:
	 rm -rf *o main
